# Generated by Django 3.2.9 on 2021-11-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0003_auto_20211117_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='army_name',
            new_name='name',
        ),
    ]
